### ISSUE TITLE
Throws an error Error [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by pramod4040** [middyjs/middy#1174]
**Describe the bug**
I'm utilizing middy alongside serverless-webpack. Previously, without serverless-webpack, middy functioned properly. However, after configuring it with serverless-webpack, I encountered an error.

The error message states: **"No 'exports' main defined in /path/to/folder/node_modules/@middy/core/package.json."** This same issue occurred with @middy/http-json-body-parser. Interestingly, the code functions correctly when middleware isn't utilized.

**To Reproduce**
serverless.yml
```
provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

functions:
  listTodo:
    handler: src/lamdahandler/LamdahandlerMgmt.ListTodoMiddy
    events:
      - http:
          path: /api/todo
          method: GET
          cors: 
            origin: "*"

custom:
  webpack:
    webpackConfig: 'webpack.config.js' 
    includeModules: false
    packager: 'npm' 
    excludeFiles: src/**/*.test.js 
```

webpack.config.js
```
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const path = require('path');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  mode: 'development',
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts']
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      }
    ]
  },
  // externals: [nodeExternals(allowlist=[
  //   "@middy/*"
  // ])],  // I have tried this.
  externals: [nodeExternals()],
  resolve: {
    extensions: ['.mjs', '.ts', '.js', '.json'],
    importsFields: ['module', 'main'],
    modules: ['node_modules']
  }
};
```
src/lamdahandler/listTodoMgmt.js
```
// import middy from '@middy/core';
import { getRecordCustom } from '../commons/utils/dbMgmt.js';
import todo from "../models/todo.js";
import { apiResponse, apiError } from '../commons/http-helpers/api-response.js';
// import httpBodyParser from '@middy/http-json-body-parser';
import { authenticateTokenMiddleware } from '../commons/middleware/middleware.js';


export const listAllTodo = async (event) => {
    try {
        let todoList = [{title: "Coding"}, {title: "Debugging"}, {title: "Asking Help"}];
        // let todoList = await getRecordCustom({}, todo);
        return {
            statusCode: 200,
            body: JSON.stringify(todoList)
        }
        // return apiResponse(todoList);
    } catch (error) {
        // return apiError(500, error.message);
        return {
            statusCode: 500,
            body: JSON.stringify({message: "Server error!"})
        }
    }
}

export const handler =  listAllTodo;   

// export const handler = middy(listAllTodo)
// .use(authenticateTokenMiddleware())
// .use(httpBodyParser())
```
** Thrown error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /path/to/folder/node_modules/@middy/core/package.json

**Environment (please complete the following information):**

- Node.js: 21.2.0
- @middy/core: 5.2.3
- @middy/http-json-body-parser: 5.2.3
- serverless-offline: 13.3.3
