### ISSUE TITLE
No response body

### ISSUE THREAD

**Issue by ciacka** [middyjs/middy#280]
I'm following the docs but have a problem with response - there is not response's body at all. I'm using serverless-offline. Example configuration and code below.

`serverless.yml`
```yaml
service: test-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  default:
    handler: src/index.list
    events:
      - http: GET /
```

`src/index.js`
```javascript
const middy = require('middy');
const { urlEncodeBodyParser, validator, httpErrorHandler } = require('middy/middlewares');

const processPayment = (event, context, callback) => {
    return callback(null, { "message": "text" });
}

const handler = middy(processPayment)
  .use(urlEncodeBodyParser()) // parses the request body when it's a JSON and converts it to an object
  .use(httpErrorHandler());

module.exports.list = handler;
```

When requesting `GET http://localhost:3000/` I receive response with `200 OK` status code but without body.

What I figured out, when I add `body` property to callback's object then response contains body, e.g.:

```javascript
const processPayment = (event, context, callback) => {
    return callback(null, { "body": JSON.stringify({"message": "text"}) });
}
```
