### ISSUE TITLE
validation error broken? maybe related to serverless-offline / serverless-webpack plugin? 

### ISSUE THREAD

**Issue by dwelch2344** [middyjs/middy#94]
Just getting started and can't seem to get validation error messages working based on the README. We're using the es7 webpack plugin + serverless-offline, but I don't think that is why.

No matter what we do, we always get a strange `Unexpected 'E'` response body. 

Tried debugging, going as far to the actual source and making sure all our middleware is hit in the correct order and everything, but no dice.

Anyone able to take a look at / spot a stupid mistake we're making? Thanks in advance

**handler.js**
```js
const middy = require('middy')
const { urlEncodeBodyParser, validator, httpErrorHandler, cors, jsonBodyParser } = require('middy/middlewares')

const dummy = (event, context, callback) => callback(
  { statusCode: 200, body: JSON.stringify({message: 'hi'})}
)
const demo = middy( dummy )
  .use(urlEncodeBodyParser()) // parses the request body when it's a JSON and converts it to an object
  .use(validator({inputSchema})) // validates the input
  .use(httpErrorHandler()) // handles common http errors and returns proper responses

module.exports = { demo }
```

**serverless.yml**
```yml
# NOTE: update this with your service name
service: demo

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline


# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  demo:    
    handler: handler.demo
    events:
      - http:
          cors: true
          path: demo/
          method: POST    
```
